name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test-parse:
    name: Data Files
    runs-on: windows-2022
    env:
      CONTINUOUS: EndlessSky-win64-continuous.zip
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Download latest continuous
      run: gh release download -R endless-sky/endless-sky continuous -p ${{ env.CONTINUOUS }}
    - name: Extract and prepare continuous
      run: |
        Expand-Archive ${{ env.CONTINUOUS }} -DestinationPath endless-sky -Force
        cd .\endless-sky
        mkdir plugins
        cd .\plugins
        mkdir toggle-endless-sky
    - uses: actions/checkout@v4
      with:
        path: '.\endless-sky\plugins\toggle-endless-sky'
    - name: Parse Datafiles
      run: "'.\\endless-sky\\Endless Sky.exe' -p"
      shell: bash
